[package]
name = "treedee"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
bresenham = "0.1.1"
rand = "0.9.2"
trig-const = "0.3.0"

[dev-dependencies]
minifb = "0.28.0"
rand = "0.9.2"
